[metadata]
name = "Ping"
description = "Simple ping test case"
author = "Daniel Stolpmann <daniel.stolpmann@tuhh.de>"

[general]
graph-file = "fixed_interval"
source-command = "ping 10.0.2.1 -c 10"
sink-command = ""

fixed_delay.delay = "[0, 10, 20]"

repetitions = 3
